# Generated by Django 5.0.6 on 2024-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
