# Generated by Django 5.0.6 on 2024-07-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_artwork_image_url_artwork_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
